version: "3"
services:

  portainer:
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 9000:9000
    container_name: portainer

  portainer_init:            
    depends_on:              
      - portainer            
    image: alpine/curl       
    restart: on-failure      
    environment:             
      - PORTAINER_PASSWORD=${PORTAINER_PASSWORD}
    volumes:                 
      - ./conf/setup.sh:/setup.sh
    command: ./setup.sh
